name: Run test
on:
  pull_request:
    branches:
      - main
      - preview
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache_dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - run: echo '${{ toJSON(steps.cache_dependencies.outputs) }}'
      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Test
        shell: bash
        run: |
          yarn format:check
          yarn lint:check
          yarn test
